ARG CODE_VERSION=latest
ARG LDAP_ADMIN_PASSWORD
ARG LDAP_ORGANISATION
ARG LDAP_DOMAIN
ARG LDAP_BASE_DN

ARG LDAP_TLS
ARG LDAP_ADMIN_PASSWORD
ARG LDAP_CONFIG_PASSWORD


FROM centos AS ldapserver-centos

RUN yum update -y
RUN yum install -y \
    httpd \
    httpd-tools \
    nano \
    openldap \
    openldap-servers


FROM ubuntu AS ldapserver-ubuntu
RUN apt update -y && apt-upgrade -y
RUN apt install -y \
    httpd \
    httpd-tools \
    nano \
    slapd ldap-utils

# FROM centos:7
# ENV container docker
# RUN (cd /lib/systemd/system/sysinit.target.wants/; for i in *; do [ $i == \
#     systemd-tmpfiles-setup.service ] || rm -f $i; done); \
#     rm -f /lib/systemd/system/multi-user.target.wants/*;\
#     rm -f /etc/systemd/system/*.wants/*;\
#     rm -f /lib/systemd/system/local-fs.target.wants/*; \
#     rm -f /lib/systemd/system/sockets.target.wants/*udev*; \
#     rm -f /lib/systemd/system/sockets.target.wants/*initctl*; \
#     rm -f /lib/systemd/system/basic.target.wants/*;\
#     rm -f /lib/systemd/system/anaconda.target.wants/*;
# VOLUME [ "/sys/fs/cgroup" ]
# CMD ["/usr/sbin/init"]