{{- if .Values.enabled }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: gitlab-config-pv
  labels:
    type: local
spec:
  storageClassName: gitlab-config
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/e/data/DeveloperSuite/gitlab/config'
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: gitlab-logs-pv
  labels:
    type: local
spec:
  storageClassName: gitlab-logs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/e/data/DeveloperSuite/gitlab/logs'
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: gitlab-data-pv
  labels:
    type: local
spec:
  storageClassName: gitlab-data
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/e/data/DeveloperSuite/gitlab/data'
{{- end }}
