version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    links:
      - elasticsearch
    ports:
      - 5601:5601

#    volumes:
#      - ../configs/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
    #  SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

#  logstash:
#    image: docker.elastic.co/logstash/logstash:7.8.0
#    volumes:
#      - ../configs/logstash/config:/usr/share/logstash/config

volumes:
  elasticsearch:
