apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: nginx
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
#  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: nginx
      tier: frontend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        tier: frontend
        track: stable
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        #volumeMounts:
        #- name: config-vol
        #  mountPath: /etc/nginx/
        ports:
        - containerPort: 80
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]
      volumes:
          - name: config-vol
            configMap:
              name: nginx-conf