version: "3.7"
services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/data
    volumes:
      - ../configs/prometheus:/etc/prometheus
      - prometheus:/data

  grafana:
    image: grafana/grafana
    links:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana:/var/lib/grafana
      - ../configs/grafana/custom.ini:/usr/share/grafana/conf/custom.ini
    command:
      - "--config=/usr/share/grafana/conf/custom.ini"
    environment:
      # grafana-simple-json-datasource | grafana-worldmap-panel | jdbranham-diagram-panel | abhisant-druid-datasource
      GF_INSTALL_PLUGINS: grafana-simple-json-datasource,grafana-worldmap-panel,jdbranham-diagram-panel,abhisant-druid-datasource,simpod-json-datasource,digiapulssi-organisations-panel,camptocamp-prometheus-alertmanager-datasource,agenty-flowcharting-panel
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug

  # Remote Rendering
  renderer:
    image: grafana/grafana-image-renderer:latest
    ports:
      - 8081:8081
#    volumes:
#      - ../grafana/renderer-config.json:/usr/src/app/config.json
    environment:
      ENABLE_METRICS: "true"

 # /usr/share/grafana/conf

volumes:
  grafana:
  prometheus:
