{{- if .Values.enabled }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: neo4j-data-pv
  labels:
    app: neo4j
    type: local
spec:
  storageClassName: neo4j-data
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/e/data/DeveloperSuite/neo4j/data'
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: neo4j-logs-pv
  labels:
    app: neo4j
    type: local
spec:
  storageClassName: neo4j-logs
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/e/data/DeveloperSuite/neo4j/logs'
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: neo4j-config-pv
  labels:
    app: neo4j
    type: local
spec:
  storageClassName: neo4j-config
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/e/data/DeveloperSuite/neo4j/config'
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: neo4j-ssl-pv
  labels:
    app: neo4j
    type: local
spec:
  storageClassName: neo4j-ssl
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/e/data/DeveloperSuite/neo4j/ssl'
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: neo4j-plugins-pv
  labels:
    app: neo4j
    type: local
spec:
  storageClassName: neo4j-plugins
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/e/data/DeveloperSuite/neo4j/plugins'
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: neo4j-imports-pv
  labels:
    app: neo4j
    type: local
spec:
  storageClassName: neo4j-imports
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/e/data/DeveloperSuite/neo4j/imports'
{{- end }}
