{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-deployment
  labels:
    app: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus
  template:
    metadata:
      labels:
        app: nexus
    spec:
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", "chown -R 200:200 /nexus-data"]
        volumeMounts:
        - name: nexus-data
          mountPath: /nexus-data
      containers:
      - name: nexus
        image: sonatype/nexus3
        ports:
        - containerPort: 8081
          name: "nexus"
        - containerPort: 5000
          name: "nexus-docker"
        - containerPort: 5001
          name: "nexus-docker2"
        volumeMounts:
        - name: nexus-data
          mountPath: '/nexus-data'
      volumes:
      - name: nexus-data
        persistentVolumeClaim:
          claimName: nexus-pvc
{{- end }}
