{{- if .Values.enabled }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: nexus-pv
  labels:
    type: local
spec:
  storageClassName: nexus
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '/e/data/DeveloperSuite/nexus'
{{- end }}
