{{- if .Values.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nexus-pvc
spec:
  storageClassName: nexus
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
{{- end }}
