{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: redis
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379
          name: "redis"
        volumeMounts:
        - name: redis-data
          mountPath: '/data'
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc
{{- end }}
