{{- if .Values.enabled }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: docker-registry-pv
  labels:
    type: local
spec:
  storageClassName: docker-registry
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: '/e/data/DeveloperSuite/docker-registry'
{{- end }}
