{{- if .Values.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: docker-registry-pvc
spec:
  storageClassName: docker-registry
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
{{- end }}
