{{- if .Values.enabled }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-pv
  labels:
    app: jenkins
    type: local
spec:
  storageClassName: jenkins
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/e/data/DeveloperSuite/jenkins'
{{- end }}
