{{- if .Values.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  type: LoadBalancer
  ports:
  - name: "jenkins"
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 8080
    # nodePort: 30408
  - name: "jenkins2"
    protocol: TCP
    port: 50000
    targetPort: 50000
    # nodePort: 30409
status:
  loadBalancer:
    ingress:
    - hostname: localhost
#    - hostname: localhost

{{- end }}
