
#FROM osixia/openldap:1.2.4
FROM osixia/openldap
LABEL maintainer="JeanMGirard@Outlook.com"

ADD objects /srv/ldap
ADD certs   /srv/ssh
ADD env     /srv/env










# ARG CODE_VERSION=latest
# ARG ROOT_PASSWD
# FROM centos:7 AS ldap-build
# ENV ROOT_PASSWD ${ROOT_PASSWD:-ldapserver}
# ADD ./objects /srv/ldap
# WORKDIR /srv/ldap
# RUN yum update -y -q
# RUN yum install -y -q openldap openldap-servers
# RUN export ROOT_PASSWD=`slappasswd -s $ROOT_PASSWD`
# RUN systemctl start slapd && systemctl enable slapd
# ONBUILD ADD . /app/src
# ONBUILD RUN systemctl status slapd
# RUN firewall-cmd --add-service=ldap
#
#
#
#FROM ubuntu AS net_ldapserver-ubun
# RUN apt install slapd ldap-utils

# ONBUILD ADD . /app/src
# ONBUILD RUN systemctl status slapd
#RUN ufw allow ldap