{{- if .Values.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: che
  labels:
    app: che
spec:
  selector:
    app: che
  type: LoadBalancer
  ports:
  - name: "che"
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 8080
    # nodePort: 30408
status:
  loadBalancer:
    ingress:
    - hostname: localhost
#    - hostname: localhost

{{- end }}
