# Default values for Neo4j.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

name: "neo4j"
enabled: true
replicas: 1
service:
  ports:
    http: 7474
    https: 7473
    bolt: 7687
    shell: 1337

tty: true
stdin: true
