version: "3.5"
services:
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - frontend
      - backend
    external_links:
      - crate-db


networks:
  frontend:
  backend:
