enabled: true
# Default values for Redis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
nameOverride: ""
fullnameOverride: ""

service:
  port: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
extraArgs:
  - --appendonly yes
