version: '3'
services:
  dmnet-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    #ports:
    #  - 1194:80
    #  - 403:403
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
      restart_policy:
        condition: always
        delay: 5s
        max_attempts: 3
        #window: 120s
