{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  labels:
    app: docker-registry
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.service.http }}
    targetPort: 5000
    # nodePort: 30400
    name: "docker-registry"
  selector:
    app: docker-registry
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost
{{- end }}
