{{- if .Values.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry-deployment
  labels:
    app: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - name: docker-registry
        image: registry:2
        ports:
        - containerPort: 5000
          name: "docker-registry"
        volumeMounts:
        - name: docker-registry-data
          mountPath: '/nexus-data'
      volumes:
      - name: docker-registry-data
        persistentVolumeClaim:
          claimName: docker-registry-pvc
      command:
      - /bin/registry
      - serve
      - /etc/docker/registry/config.yml
{{- end }}
