{{- if .Values.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  type: LoadBalancer
  ports:
  - name: mongo
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 8081
status:
  loadBalancer:
    ingress:
    - hostname: localhost
#    - hostname: localhost

{{- end }}
