{{- if .Values.enabled }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-data-pv
  labels:
    app: mongo
    type: local
spec:
  storageClassName: mongo-data
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: '/e/data/DeveloperSuite/MongoDB'
{{- end }}
