version: '2'
services:
  openvpn:
    image: kylemanna/openvpn
    container_name: openvpn
    cap_add:
     - NET_ADMIN
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - ./data/default:/etc/openvpn
