version: '3.4'
services:
  openldap:
    image: osixia/openldap:1.2.4
    container_name: net-openldap
    env_file: .env
    tty: true
    stdin_open: true
    ports:
      - "389:389"
      - "636:636"