{{- if .Values.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: LoadBalancer
  selector:
    app: redis
  ports:
  - name: "redis"
    protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 6379
    # nodePort: 30408

status:
  loadBalancer:
    ingress:
    - hostname: localhost

{{- end }}
