{{- if .Values.enabled }}
{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-ingress
  labels:
    app: jenkins
spec:
  rules:
  - host: localhost
    http:
      paths:
        - path: /
          backend:
            serviceName: jenkins-http
            servicePort: 8080
{{- end -}}
{{- end -}}
