{{- if .Values.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-config-pvc
spec:
  storageClassName: gitlab-config
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-logs-pvc
spec:
  storageClassName: gitlab-logs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-data-pvc
spec:
  storageClassName: gitlab-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{{- end }}
