# Default values for MongoDB.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
enabled: true
replicaCount: 1


nameOverride: "mongo"
fullnameOverride: "mongo"
tty: true
stdin: true
service:
  port: 8081


resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
