version: "3.2"

services:
  coredns:
    image: coredns/coredns
  #  command: -conf /data/Corefile
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "9153:9153/tcp"
  #  volumes:
  #    - ./data:/etc/coredns
    cap_add:
      - NET_BIND_SERVICE
    deploy:
      restart_policy:
        condition: on-failure
